apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/consumer-mh:hubert
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
