apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: front-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/frontend-mh:hubert
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
